#!/bin/bash
## stuff from jobheader.sh
#PBS -N qsiprep

set -x
set -e


    
echo "done with qsiprep! - now organizing output"
./qsiprep2bl.sh

rm -r $WORKDIRNAME # save lots of space    

echo "all done!" 
